#!/bin/sh

yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/board/map-red-dark.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/board/playerboard.config.json 

yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/action/action.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/court/court.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/leader/leader.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/lore/lore.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/setup/2p/2p.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/setup/3p/3p.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i prebuild/base/card/setup/4p/4p.config.json

yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i  prebuild/leaders-and-lore/card/leader/leader.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-cardsheets/create-cardsheet-run.ts -i  prebuild/leaders-and-lore/card/lore/lore.config.json

yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/action-face-up.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/agent.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/building.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/court.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/court-deck-discard.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/dice.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/leader.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/lore.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/resource.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-board/create-board-run.ts -i prebuild/base/mat/ship.config.json

yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-d6/create-d6-run.ts -i  prebuild/base/dice/assault/assault.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-d6/create-d6-run.ts -i  prebuild/base/dice/raid/raid.config.json
yarn ts-node ../ttpg-darrell/src/lib-ext/create-assets/create-d6/create-d6-run.ts -i  prebuild/base/dice/skirmish/skirmish.config.json

yarn ts-node ../ttpg-darrell/src/lib-ext/nsid/extract-nsid-to-template-id.ts -i assets/Templates -o src/global/inject-spawn-nsids/auto-nsid-to-template-id.json
