#!/bin/sh

../ttpg-darrell/tooling/generators/create-board.ts -f prebuild/base/board/map-red-dark.config.json
../ttpg-darrell/tooling/generators/create-board.ts -f prebuild/base/board/playerboard.config.json

../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/action/action.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/court/court.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/leader/leader.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/lore/lore.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/setup/2p/2p.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/setup/3p/3p.config.json
../ttpg-darrell/tooling/generators/create-deck.ts -f prebuild/base/card/setup/4p/4p.config.json

../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/agent.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/building.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/court.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/dice.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/leader.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/lore.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/resource.config.json
../ttpg-darrell/tooling/generators/create-card-mat.ts -f prebuild/base/mat/ship.config.json

../ttpg-darrell/tooling/generators/create-dice.ts -f prebuild/base/dice/assault/assault.config.json
../ttpg-darrell/tooling/generators/create-dice.ts -f prebuild/base/dice/raid/raid.config.json
../ttpg-darrell/tooling/generators/create-dice.ts -f prebuild/base/dice/skirmish/skirmish.config.json
